# Generated by Django 2.0.2 on 2021-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210419_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExeMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='执行机名称')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='执行机IP')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('status', models.SmallIntegerField(choices=[(0, '正常'), (1, '关机'), (2, '故障'), (3, '占用')], default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '执行机',
                'verbose_name_plural': '执行机',
            },
        ),
    ]
