# Generated by Django 2.0.2 on 2021-04-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exemachine'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemachine',
            name='type',
            field=models.CharField(blank=True, choices=[('Linux', 'Linux'), ('Windows', 'Windos')], default='Windows', max_length=64, null=True, verbose_name='执行机类型'),
        ),
        migrations.AlterField(
            model_name='exemachine',
            name='status',
            field=models.CharField(choices=[('正常', '正常'), ('关机', '关机'), ('故障', '故障'), ('占用', '占用')], default='正常', max_length=32, verbose_name='状态'),
        ),
    ]
